MvcPL/ViewModels/LogOnViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcPL.ViewModels
{
    public class LogOnViewModel
    {
        [Required(ErrorMessage = "The field can not be empty!")]
        [Display(Name = "Enter your e-mail")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Invalid email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "The field can not be empty!")]
        [DataType(DataType.Password)]
        [Display(Name = "Enter your password")]
        public string Password { get; set; }

        [Display(Name = "Remember password?")]
        public bool RememberMe { get; set; }
    }
}

MvcPL/Controllers/AdminController.cs
using BLL.Interface.Entities;
using BLL.Interface.Services;
using MvcPL.ViewModels;
using MvcPL.Infrastructure.Mappers;
using System.Linq;
using System.Web.Mvc;
using System;
using System.Collections.Generic;

namespace MvcPL.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        #region Fields
        private readonly IUserService userService;
        #endregion

        #region Ctors
        public AdminController(IUserService service)
        {
            userService = service;
        }
        #endregion

        #region Public Methods

        [ActionName("Index")]
        public ActionResult UsersEdit(int page = 0)
        {
            int pageSize = 10;
            var users = new PagedData<UserViewModel>();
            var allusers = userService.GetAllUserEntities();
            users = GetCountOfUsers(pageSize, page, allusers);      
            
            if (HttpContext.Request.IsAjaxRequest())
                return PartialView(users);
            else
                return View(users);
        }

        private PagedData<UserViewModel> GetCountOfUsers(int pageSize, int page, IEnumerable<UserEntity> allusers)
        {
            var resultUsers = new PagedData<UserViewModel>();
            if (page > 0)
            {
                resultUsers.Data = GetUsersData(pageSize, page);
                resultUsers.CurrentPage = page;
            }
            else
            {
                resultUsers.Data = GetFirstPageUsersData(pageSize, page); 
                resultUsers.CurrentPage = 1;
            }

            resultUsers.NumberOfPages = allusers.Count() % pageSize == 0 ? allusers.Count() / pageSize : allusers.Count() / pageSize + 1;
            return resultUsers;
        }

        private IEnumerable<UserViewModel> GetFirstPageUsersData(int pageSize, int page)
        {
            var users = userService.GetAllUserEntities().Select(user => new UserViewModel
            {
                UserId = user.UserId,
                Email = user.Email,
                CreatedOn = user.CreatedOn
            }).Take(pageSize)
                        .ToList();
            return users;
        }

        private IEnumerable<UserViewModel> GetUsersData(int pageSize, int page)
        {
            var users = userService.GetAllUserEntities().Select(user => new UserViewModel
            {
                UserId = user.UserId,
                Email = user.Email,
                CreatedOn = user.CreatedOn
            }).Skip(pageSize * (page - 1))
                        .Take(pageSize)
                        .ToList();
            return users;
        }

        public ActionResult Details(int userId)
        {
            var user = userService.GetUserEntity(userId).ToMvcUser();
            return View(user);
        }

        [HttpGet]
        public ActionResult DeleteUser(int id)
        {
            UserEntity user = userService.GetUserEntity(id);
            userService.DeleteUser(user);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            UserEntity user = userService.GetUserEntity(id);
            if (user == null)
                return HttpNotFound();

            return View(user.ToMvcUser());
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserEntity user = userService.GetUserEntity(id);
            userService.DeleteUser(user);
            return RedirectToAction("Index");
        }

        #endregion
    }
}

MvcPL/Controllers/CategoryController.cs
using BLL.Interface.Services;
using MvcPL.Infrastructure.Mappers;
using MvcPL.Infrastructure.Attributes;
using MvcPL.Infrastructure.Utilities;
using MvcPL.ViewModels;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interface.Entities;

namespace MvcPL.Controllers
{
    public class CategoryController : Controller
    {
        #region Fields
        private readonly ICategoryPhotoService categoryService;
        #endregion

        #region Ctors
        public CategoryController(ICategoryPhotoService service)
        {
            categoryService = service;
        }
        #endregion

        #region Public Methods

        [Authorize]
        [HttpGet]
        public ActionResult CreateCategory()
        {
            if (Request.QueryString["content"] != null)
                return PartialView();
            else
                return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory(CategoryPhotoViewModel ctgrPhotoViewModel, string returnUrl)
        {
            if (categoryService.GetCategoryIdByName(ctgrPhotoViewModel.Name) != 0)
            {
                ModelState.AddModelError("", "Category already exists.");
                if (HttpContext.Request.IsAjaxRequest())
                    return Json(new { errors = GetErrorsFromModelState() });                
                return View(ctgrPhotoViewModel);
            }

            categoryService.CreateCategoryPhoto(ctgrPhotoViewModel.ToBllCategory());
            if (HttpContext.Request.IsAjaxRequest())
                return Json(new { success = true, redirect = returnUrl });
            return RedirectToAction("Index", "Photo");
        }

        public JsonResult ValidateCategoryName(string Name)
        {
            var anyCategory = categoryService.GetCategoryIdByName(Name);
            return Json(anyCategory == 0, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAllCategoryPhoto(int id = 1)
        {
            var result = categoryService.GetAllCategoryPhotoEntities().Select(ctgrPhoto => ctgrPhoto.ToMvcCtgrPhoto());
            var rslt = result.ToList().Select(c => new
            {
                CategoryName = c.Name,
                CategoryId = c.Id,
                Selected = false
            }).ToList();

            ViewBag.CategoryPhoto = new SelectList(rslt, "CategoryId", "CategoryName");

            return View();
        }

        public string GetCategory(int categoryId)
        {
            var category = categoryService.GetCategoryPhotoEntity(categoryId);

            return category.Name;
        }

        #endregion

        #region Private Methods
        private IEnumerable<string> GetErrorsFromModelState()
        {
            return ModelState.SelectMany(x => x.Value.Errors.Select(error => error.ErrorMessage));
        }
        #endregion
    }
}

MvcPL/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interface.Entities;
using BLL.Interface.Services;
using MvcPL.Infrastructure.Mappers;
using MvcPL.Infrastructure.Attributes;
using MvcPL.Infrastructure.Utilities;
using MvcPL.ViewModels;
using System.IO;
using System.Drawing.Imaging;

namespace MvcPL.Controllers
{
    public class PhotoController : Controller
    {
        #region Fields
        private readonly ICategoryPhotoService categoryService;
        private readonly IVotingService votingService;
        private readonly IPhotoService photoService;
        private readonly IUserService userService;
        #endregion

        #region Ctors
        public PhotoController(ICategoryPhotoService service, IPhotoService phService, IUserService usrService, IVotingService voteService)
        {
            categoryService = service;
            photoService = phService;
            userService = usrService;
            votingService = voteService;
        }
        #endregion

        #region Public Methods

        public ActionResult Index(int page = 1, int Id = 0)
        {
            int pageSize = 6;
            dynamic photosPerPages;
            if (Id > 0)
                photosPerPages = photoService.GetAllPhotoEntities().Where(ph => ph.CategoryId == Id).Select(photo => photo.ToMvcPhoto()).Skip((page - 1) * pageSize).Take(pageSize);
            else
                photosPerPages = photoService.GetAllPhotoEntities().Select(photo => photo.ToMvcPhoto()).Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = pageSize,
                TotalItems = photoService.GetAllPhotoEntities().Count()
            };

            IndexViewModel ivm = new IndexViewModel
            {
                PageInfo = pageInfo,
                Photos = photosPerPages
            };
            if (HttpContext.Request.IsAjaxRequest())
                return PartialView(ivm);
            return View(ivm);
        }

        [Authorize]
        public ActionResult GetPhotoForUser(int page = 0)
        {
            int pageSize = 3;
            int userId = userService.GetUserByEmail(User.Identity.Name).UserId;
            var photos = new PagedData<PhotoViewModel>();

            var allPhotos = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .ToList();

            if (page > 0)
            {
                photos.Data = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .Skip(pageSize * (page - 1))
                        .Take(pageSize)
                        .ToList();
                photos.CurrentPage = page;
            }
            else
            {
                photos.Data = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .Take(pageSize)
                        .ToList();
                photos.CurrentPage = 1;
            }
            photos.NumberOfPages = allPhotos.Count() % pageSize == 0 ? allPhotos.Count() / pageSize : allPhotos.Count() / pageSize + 1;


            return View(photos);
        }

        public ActionResult PhotosList(int page)
        {
            int pageSize = 3;
            int userId = userService.GetUserByEmail(User.Identity.Name).UserId;
            var photos = new PagedData<PhotoViewModel>();

            var allPhotos = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .ToList();

            photos.Data = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .Skip(pageSize * (page - 1))
                        .Take(pageSize)
                        .ToList();

            photos.NumberOfPages = allPhotos.Count() % pageSize == 0 ? allPhotos.Count() / pageSize : allPhotos.Count() / pageSize + 1;
            photos.CurrentPage = page;

            return PartialView(photos);
        }

        public ActionResult LastPhotos(string userName = null)
        {
            int userId = 0;
            if (userName == null)
                userId = userService.GetUserByEmail(User.Identity.Name).UserId;
            else
                userId = userService.GetUserByEmail(userName).UserId;
            var allPhotos = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .ToList();

            var lastphotos = allPhotos.Skip(Math.Max(0, allPhotos.Count() - 6));

            return PartialView(lastphotos);
        }

        /// <summary>
        /// Method Photos dynamic load photos to main page.
        /// </summary>
        /// <param name="photoId">Id of last photos in main page.</param>
        /// <returns>Next 3 photos to main page.</returns>
        [HttpPost]
        public ActionResult Photos(int photoId, int Id = 0)
        {
            var photos = default(IEnumerable<PhotoViewModel>);
            if(Id > 0)
               photos = photoService.GetAllPhotoEntities().Select(photo => photo.ToMvcPhoto()).
                    Where(p => p.Id > photoId && p.CategoryId == Id).Take(3);
            else
               photos = photoService.GetAllPhotoEntities().Select(photo => photo.ToMvcPhoto()).
                    Where(p => p.Id > photoId).Take(3);
            if (photos.IsEmpty<PhotoViewModel>())
                return null;
            return PartialView("_Photos", photos);
        }

        [Authorize]
        [HttpGet]
        public ActionResult CreatePhoto()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreatePhoto(PhotoViewModel photo, IEnumerable<HttpPostedFileBase> files, string Id)
        {
            if (!ModelState.IsValid)
                return View(photo);
            if (files.Count() == 0 || files.FirstOrDefault() == null)
            {
                ViewBag.error = "Please choose a file";
                return View(photo);
            }

            PhotoViewModel model = new PhotoViewModel();
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {
                    model.Image = Images.GetImageNewSize(file);
                }

                model.Description = photo.Description;
                model.CreatedOn = DateTime.Now;
                model.CategoryId = Convert.ToInt32(Id);
                model.UserId = userService.GetUserByEmail(User.Identity.Name).UserId;
                photoService.CreatePhoto(model.ToBllPhoto());
            }

            return RedirectToAction("GetPhotoForUser");
        }

        [Authorize]
        [HttpGet]
        public ActionResult EditPhoto(int photoId)
        {
            var photo = photoService.GetPhotoEntity(photoId).ToMvcPhoto();
            return View(photo);
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditPhoto(PhotoViewModel photo, int photoId, int id)
        {
            if (ModelState.IsValid)
            {
                photo.Id = photoId;
                photo.CategoryId = id;
                photoService.UpdatePhoto(photo.ToBllPhoto());
                TempData["message"] = string.Format("Photo {0}  has been updated.", photo.Description);
                return RedirectToAction("GetPhotoForUser");
            }

            return View(photo);
        }

        [HttpGet]
        public ActionResult DeletePhoto(int id)
        {
            PhotoEntity photo = photoService.GetPhotoEntity(id);

            if (photo == null)
                return HttpNotFound();

            return View(photo.ToMvcPhoto());
        }

        [HttpPost, ActionName("DeletePhoto")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhotoEntity photo = photoService.GetPhotoEntity(id);
            TempData["message"] = string.Format("Photo has been deleted.", photo.Description);
            photoService.DeletePhoto(photo);
            return RedirectToAction("GetPhotoForUser");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            PhotoEntity photo = photoService.GetPhotoEntity(id);
            TempData["message"] = string.Format("Photo has been deleted.", photo.Description);
            photoService.DeletePhoto(photo);            
            return RedirectToAction("GetPhotoForUser");
        }

        public ActionResult FindByDescription(string term)
        {

            var photos = photoService.GetAllPhotoEntities().Where(photo => photo.Description.ToLower().Contains(term.ToLower()));
            var results = photos.Select(photo =>
                new
                {
                    id = photo.Id,
                    label = photo.Description
                });

            var jsonResult = Json(results.ToList(), JsonRequestBehavior.AllowGet);

            return jsonResult;
        }

        [HttpGet]
        public ActionResult Find()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Find(string term)
        {
            IEnumerable<PhotoViewModel> photos = photoService.GetAllPhotoEntities().Where(photo => photo.Description.ToLower().Contains(term.ToLower()) || photo.Description.ToLower() == term.ToLower()).
                Select(photo => new PhotoViewModel { CreatedOn = photo.CreatedOn, CategoryId = photo.CategoryId, Id = photo.Id });

            return View(photos);
        }

        public JsonResult PhotoListBySearch(string search)
        {
            var photos = photoService.GetAllPhotoEntities().Where(photo => photo.Description.ToLower().Contains(search.ToLower())).

MvcPL/Views/Shared/LogOn.cshtml
@model MvcPL.ViewModels.LogOnViewModel

@{
    ViewBag.Title = "LogOn";
    Layout = null;
}

@using (Html.BeginForm("LogOn", "Account", FormMethod.Post, new { id = "login-form" }))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Email, new { @placeholder = "Email" })
        @Html.ValidationMessageFor(model => model.Email)
    </div>
    <div class="editor-field">
        @Html.PasswordFor(model => model.Password, new { @placeholder = "Password" })
        @Html.ValidationMessageFor(model => model.Password)
    </div>
    <input type="submit" name="loginBtn" form="login-form" id="loginBtn" value="Go" />
}

MvcPL/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/_PhotoLayout.cshtml";
}

<div class="error-div">
    <p class="error-code">404</p>
    <p class="error-404-text">
        Page not found!
    </p>
    <img src="~/Content/images/error.gif" style="display:block;" />
    @Html.ActionLink("Go Back To Home Page", "Index", "Photo")
</div>

MvcPL/Views/Shared/_LogOn.cshtml
@model MvcPL.ViewModels.LogOnViewModel

@{
    ViewBag.Title = "LogOn";
    Layout = null;
}

@using (Html.BeginForm("LogOn", "Account", FormMethod.Post, new { id = "login-form" }))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Email, new { @placeholder = "Email" })
        @Html.ValidationMessageFor(model => model.Email)
    </div>
    <div class="editor-field">
        @Html.PasswordFor(model => model.Password, new { @placeholder = "Password" })
        @Html.ValidationMessageFor(model => model.Password)
    </div>
    <input type="submit" name="loginBtn" form="login-form" id="loginBtn" value="Go" />
}

MvcPL/Views/Shared/_Login.cshtml
@using MvcPL.ViewModels
@model LogOnViewModel

<div id="login" class="login">
    @{
        if (Request.IsAuthenticated)
        {
            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
            {
                <div class="dropdown">
                    <span>Hi, @User.Identity.Name</span>
                        <div class="dropdown-content">
                            <input type="submit" title="Log Out" value="Log Out" class="logout-btn">
                        </div>
                </div>
            }
        }
        else
        {
             @Html.ActionLink("Log in", "LogOn", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", data_dialog_width = 300 })
        }
    }
    </div>

MvcPL/Views/Shared/_PhotoLayout.cshtml
@using MvcPL.ViewModels
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="icon" href="~/Content/images/icon.png" />
</head>
<body>
    <div class="clearfix">
        <header class="clearfix">
            <div class="logo-div">
                <a href="/"><img src="~/Content/images/logo.png" class="logo nav" alt="Logo" /></a>
            </div>
            <nav>
                <ul class="topnav" id="topnav">
                    <li id="first-li">
                        @Html.ActionLink("Home", "Index", "Photo", routeValues: null, htmlAttributes: new { @class = "nav" })
                        <ul>
                            <li class="nav-li">@Html.ActionLink("About", "About", "Home", routeValues: null, htmlAttributes: new { @class = "nav" })</li>
                            <li class="nav-li">@Html.ActionLink("Contact", "Contact", "Home", routeValues: null, htmlAttributes: new { id = "contactLink", @class = "nav", data_dialog_width = 340 })</li>
                            @{
                                if (@User.IsInRole("User"))
                                {
                                    <li class="nav-li">@Html.RouteLink("My Photo", "userphotos", routeValues: null, htmlAttributes: new { @class = "nav" })</li>
                                }
                                else
                                {
                                    <li class="nav-li">@Html.RouteLink("Registry", "register", routeValues: null, htmlAttributes: new { id = "registerLink", data_dialog_width = 400 })</li>
                                }
                            }
                            @{
                                if (@User.IsInRole("Administrator"))
                                {
                                    <li class="nav-li">@Html.ActionLink("Users", "Index", "Admin", routeValues: null, htmlAttributes: new { @class = "nav" })</li>
                                }
                            }
                        </ul>
                    </li>
                    <li id="last-li" class="right-float">@Html.Partial("_Login", new LogOnViewModel())</li>
                </ul>
            </nav>
            <section id="search">
                @{
                    using (Html.BeginForm("Find", "Photo", FormMethod.Post, new { id = "search-form" }))
                    {
                        @Html.AntiForgeryToken()
                        <input type="text" id="photo" name="term" placeholder="Search" />
                        <input type="submit" name="search-btn" form="search-form" id="get-photos" value="" />
                    }
                }
            </section>
            <section id="filter">
            @using (Ajax.BeginForm("Index", "Photo", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "allphoto" }))
            {
                <div>
                    @{Html.RenderAction("GetAllCategoryPhoto", "Category");}
                    <input type="submit" class="button btn" style="border:1px solid lightgray; width:50%;" value="Display" />
                </div>
            }
            </section>
        </header>
        <main class="main-content">
            @RenderBody()
        </main>
    </div>
    <footer>
        <nav>
            <ul class="footer-nav">
                <li>@Html.ActionLink("Home", "Index", "Photo", null, new { @class = "nav" })</li>
                <li>@Html.ActionLink("About", "About", "Home", null, new { @class = "nav" })</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home", routeValues: null, htmlAttributes: new { id = "contactLink2", @class = "nav", data_dialog_width = 340 })</li>
                @{
                    if (@User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("My Photo", "GetPhotoForUser", "Photo", null, new { @class = "nav" })</li>
                    }
                    else
                    {
                        <li>@Html.RouteLink("Registry", "register", routeValues: null, htmlAttributes: new { id = "registerLink2", data_dialog_width = 400 })</li>
                    }
                }
                @{
                    if (@User.IsInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Users", "Index", "Admin", null, new { @class = "nav" })</li>
                    }
                }
            </ul>
        </nav>
        <p>&copy; @DateTime.Now.Year - Lehkova Natalia</p>
        <a href="/" class="nav"><img src="~/Content/images/logo.png" class="footer-logo" alt="Logo" /></a>
    </footer>
    <a href="#" class="scrollToTop"></a>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)    
</body>
</html>