MvcPL/Controllers/AdminController.cs
using BLL.Interface.Entities;
using BLL.Interface.Services;
using MvcPL.ViewModels;
using MvcPL.Infrastructure.Mappers;
using System.Linq;
using System.Web.Mvc;
using System;
using System.Collections.Generic;

namespace MvcPL.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        #region Fields
        private readonly IUserService userService;
        #endregion

        #region Ctors
        public AdminController(IUserService service)
        {
            userService = service;
        }
        #endregion

        #region Public Methods

        [ActionName("Index")]
        public ActionResult UsersEdit(int page = 0)
        {
            int pageSize = 10;
            var users = new PagedData<UserViewModel>();
            var allusers = userService.GetAllUserEntities();
            users = GetCountOfUsers(pageSize, page, allusers);      
            
            if (HttpContext.Request.IsAjaxRequest())
                return PartialView(users);
            else
                return View(users);
        }

        private PagedData<UserViewModel> GetCountOfUsers(int pageSize, int page, IEnumerable<UserEntity> allusers)
        {
            var resultUsers = new PagedData<UserViewModel>();
            if (page > 0)
            {
                resultUsers.Data = GetUsersData(pageSize, page);
                resultUsers.CurrentPage = page;
            }
            else
            {
                resultUsers.Data = GetFirstPageUsersData(pageSize, page); 
                resultUsers.CurrentPage = 1;
            }

            resultUsers.NumberOfPages = allusers.Count() % pageSize == 0 ? allusers.Count() / pageSize : allusers.Count() / pageSize + 1;
            return resultUsers;
        }

        private IEnumerable<UserViewModel> GetFirstPageUsersData(int pageSize, int page)
        {
            var users = userService.GetAllUserEntities().Select(user => new UserViewModel
            {
                UserId = user.UserId,
                Email = user.Email,
                CreatedOn = user.CreatedOn
            }).Take(pageSize)
                        .ToList();
            return users;
        }

        private IEnumerable<UserViewModel> GetUsersData(int pageSize, int page)
        {
            var users = userService.GetAllUserEntities().Select(user => new UserViewModel
            {
                UserId = user.UserId,
                Email = user.Email,
                CreatedOn = user.CreatedOn
            }).Skip(pageSize * (page - 1))
                        .Take(pageSize)
                        .ToList();
            return users;
        }

        public ActionResult Details(int userId)
        {
            var user = userService.GetUserEntity(userId).ToMvcUser();
            return View(user);
        }

        [HttpGet]
        public ActionResult DeleteUser(int id)
        {
            UserEntity user = userService.GetUserEntity(id);
            userService.DeleteUser(user);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            UserEntity user = userService.GetUserEntity(id);
            if (user == null)
                return HttpNotFound();

            return View(user.ToMvcUser());
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserEntity user = userService.GetUserEntity(id);
            userService.DeleteUser(user);
            return RedirectToAction("Index");
        }

        #endregion
    }
}

MvcPL/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interface.Entities;
using BLL.Interface.Services;
using MvcPL.Infrastructure.Mappers;
using MvcPL.Infrastructure.Attributes;
using MvcPL.Infrastructure.Utilities;
using MvcPL.ViewModels;
using System.IO;
using System.Drawing.Imaging;

namespace MvcPL.Controllers
{
    public class PhotoController : Controller
    {
        #region Fields
        private readonly ICategoryPhotoService categoryService;
        private readonly IVotingService votingService;
        private readonly IPhotoService photoService;
        private readonly IUserService userService;
        #endregion

        #region Ctors
        public PhotoController(ICategoryPhotoService service, IPhotoService phService, IUserService usrService, IVotingService voteService)
        {
            categoryService = service;
            photoService = phService;
            userService = usrService;
            votingService = voteService;
        }
        #endregion

        #region Public Methods

        public ActionResult Index(int page = 1, int Id = 0)
        {
            int pageSize = 6;
            dynamic photosPerPages;
            if (Id > 0)
                photosPerPages = photoService.GetAllPhotoEntities().Where(ph => ph.CategoryId == Id).Select(photo => photo.ToMvcPhoto()).Skip((page - 1) * pageSize).Take(pageSize);
            else
                photosPerPages = photoService.GetAllPhotoEntities().Select(photo => photo.ToMvcPhoto()).Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = pageSize,
                TotalItems = photoService.GetAllPhotoEntities().Count()
            };

            IndexViewModel ivm = new IndexViewModel
            {
                PageInfo = pageInfo,
                Photos = photosPerPages
            };
            if (HttpContext.Request.IsAjaxRequest())
                return PartialView(ivm);
            return View(ivm);
        }

        [Authorize]
        public ActionResult GetPhotoForUser(int page = 0)
        {
            int pageSize = 3;
            int userId = userService.GetUserByEmail(User.Identity.Name).UserId;
            var photos = new PagedData<PhotoViewModel>();

            var allPhotos = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .ToList();

            if (page > 0)
            {
                photos.Data = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .Skip(pageSize * (page - 1))
                        .Take(pageSize)
                        .ToList();
                photos.CurrentPage = page;
            }
            else
            {
                photos.Data = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .Take(pageSize)
                        .ToList();
                photos.CurrentPage = 1;
            }
            photos.NumberOfPages = allPhotos.Count() % pageSize == 0 ? allPhotos.Count() / pageSize : allPhotos.Count() / pageSize + 1;


            return View(photos);
        }

        public ActionResult PhotosList(int page)
        {
            int pageSize = 3;
            int userId = userService.GetUserByEmail(User.Identity.Name).UserId;
            var photos = new PagedData<PhotoViewModel>();

            var allPhotos = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .ToList();

            photos.Data = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .Skip(pageSize * (page - 1))
                        .Take(pageSize)
                        .ToList();

            photos.NumberOfPages = allPhotos.Count() % pageSize == 0 ? allPhotos.Count() / pageSize : allPhotos.Count() / pageSize + 1;
            photos.CurrentPage = page;

            return PartialView(photos);
        }

        public ActionResult LastPhotos(string userName = null)
        {
            int userId = 0;
            if (userName == null)
                userId = userService.GetUserByEmail(User.Identity.Name).UserId;
            else
                userId = userService.GetUserByEmail(userName).UserId;
            var allPhotos = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .ToList();

            var lastphotos = allPhotos.Skip(Math.Max(0, allPhotos.Count() - 6));

            return PartialView(lastphotos);
        }

        /// <summary>
        /// Method Photos dynamic load photos to main page.
        /// </summary>
        /// <param name="photoId">Id of last photos in main page.</param>
        /// <returns>Next 3 photos to main page.</returns>
        [HttpPost]
        public ActionResult Photos(int photoId, int Id = 0)
        {
            var photos = default(IEnumerable<PhotoViewModel>);
            if(Id > 0)
               photos = photoService.GetAllPhotoEntities().Select(photo => photo.ToMvcPhoto()).
                    Where(p => p.Id > photoId && p.CategoryId == Id).Take(3);
            else
               photos = photoService.GetAllPhotoEntities().Select(photo => photo.ToMvcPhoto()).
                    Where(p => p.Id > photoId).Take(3);
            if (photos.IsEmpty<PhotoViewModel>())
                return null;
            return PartialView("_Photos", photos);
        }

        [Authorize]
        [HttpGet]
        public ActionResult CreatePhoto()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreatePhoto(PhotoViewModel photo, IEnumerable<HttpPostedFileBase> files, string Id)
        {
            if (!ModelState.IsValid)
                return View(photo);
            if (files.Count() == 0 || files.FirstOrDefault() == null)
            {
                ViewBag.error = "Please choose a file";
                return View(photo);
            }

            PhotoViewModel model = new PhotoViewModel();
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {
                    model.Image = Images.GetImageNewSize(file);
                }

                model.Description = photo.Description;
                model.CreatedOn = DateTime.Now;
                model.CategoryId = Convert.ToInt32(Id);
                model.UserId = userService.GetUserByEmail(User.Identity.Name).UserId;
                photoService.CreatePhoto(model.ToBllPhoto());
            }

            return RedirectToAction("GetPhotoForUser");
        }

        [Authorize]
        [HttpGet]
        public ActionResult EditPhoto(int photoId)
        {
            var photo = photoService.GetPhotoEntity(photoId).ToMvcPhoto();
            return View(photo);
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditPhoto(PhotoViewModel photo, int photoId, int id)
        {
            if (ModelState.IsValid)
            {
                photo.Id = photoId;
                photo.CategoryId = id;
                photoService.UpdatePhoto(photo.ToBllPhoto());
                TempData["message"] = string.Format("Photo {0}  has been updated.", photo.Description);
                return RedirectToAction("GetPhotoForUser");
            }

            return View(photo);
        }

        [HttpGet]
        public ActionResult DeletePhoto(int id)
        {
            PhotoEntity photo = photoService.GetPhotoEntity(id);

            if (photo == null)
                return HttpNotFound();

            return View(photo.ToMvcPhoto());
        }

        [HttpPost, ActionName("DeletePhoto")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhotoEntity photo = photoService.GetPhotoEntity(id);
            TempData["message"] = string.Format("Photo has been deleted.", photo.Description);
            photoService.DeletePhoto(photo);
            return RedirectToAction("GetPhotoForUser");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            PhotoEntity photo = photoService.GetPhotoEntity(id);
            TempData["message"] = string.Format("Photo has been deleted.", photo.Description);
            photoService.DeletePhoto(photo);            
            return RedirectToAction("GetPhotoForUser");
        }

        public ActionResult FindByDescription(string term)
        {

            var photos = photoService.GetAllPhotoEntities().Where(photo => photo.Description.ToLower().Contains(term.ToLower()));
            var results = photos.Select(photo =>
                new
                {
                    id = photo.Id,
                    label = photo.Description
                });

            var jsonResult = Json(results.ToList(), JsonRequestBehavior.AllowGet);

            return jsonResult;
        }

        [HttpGet]
        public ActionResult Find()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Find(string term)
        {
            IEnumerable<PhotoViewModel> photos = photoService.GetAllPhotoEntities().Where(photo => photo.Description.ToLower().Contains(term.ToLower()) || photo.Description.ToLower() == term.ToLower()).
                Select(photo => new PhotoViewModel { CreatedOn = photo.CreatedOn, CategoryId = photo.CategoryId, Id = photo.Id });

            return View(photos);
        }

        public JsonResult PhotoListBySearch(string search)
        {
            var photos = photoService.GetAllPhotoEntities().Where(photo => photo.Description.ToLower().Contains(search.ToLower())).

MvcPL/Views/Admin/Delete.cshtml
@model MvcPL.ViewModels.UserViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_PhotoLayout.cshtml";
}

<div class="central-div">
    <h4>Delete User</h4>
    <hr>
    <div style="width:50%; margin:0 auto;">
        <div>Are you sure you want to delete user with login <b>@Html.DisplayFor(model => model.Email)</b>?</div>
        <br>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <p class="btn" style="padding:0.3rem 0.9rem; width:50%; border:1px solid lightgray; float:right;">
                @Html.ActionLink("Back to user's list", "Index")
            </p>
            <p style="float:right; width:50%;">
                <input style="border:1px solid lightgray; width:100%;" type="submit" value="Delete" />
            </p>
        }
    </div>
</div>

MvcPL/Views/Admin/Details.cshtml
@model MvcPL.ViewModels.UserViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_PhotoLayout.cshtml";
}

<div class="central-div">
    <h4>Details</h4>
    <hr>
    @Html.ActionLink("Back to user's list", "Index", "Admin", null, new { @class = "btn" })
    <div class="clearfix" style="width:40%; margin:0 auto;">
        <img src="@Url.RouteUrl("userimg", new { email = Model.Email })" alt="User Photo" class="left-float" style="margin-right:1rem;">
        <div>Date of user's registration: @Html.DisplayFor(modelItem => Model.CreatedOn)</div>
        @{
            var roles = Html.Action("GetRolesForUser", "Account", new { userId = Model.UserId });
            <div>Roles: @Convert.ToString(roles)</div>
        }
    </div>
    <br>
    Last added photos
    <div style="width:100%">
        @{Html.RenderAction("LastPhotos", "Photo", new { userName = Model.Email });}
    </div>
</div>

MvcPL/Views/Admin/Index.cshtml
@model MvcPL.ViewModels.PagedData<MvcPL.ViewModels.UserViewModel>

@{
    ViewBag.Title = "Users";
}
<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/load-user-photos.js"></script>
<script src="~/Scripts/dialog-login-registry.js"></script>
<script src="~/Scripts/confirm-delete.js"></script>
<div id="users-list">
    <div class="central-div">
        <h4>List of users</h4>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayName("Email")
                </th>
                <th>
                    @Html.DisplayName("CreatedOn")
                </th>
                <th>
                    @Html.DisplayName("Roles")
                </th>
                <th></th>
            </tr>
            @foreach (var item in Model.Data)
            {
                <tr>
                    <td>
                        @Html.RouteLink(item.Email, "usersdetails", new { userId = item.UserId }, new { @class = "email" })
                        <div class="user-description">
                            <img src="@Url.RouteUrl("userimg", new { email = item.Email })" alt="User Photo">
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @{
                            var roles = Html.Action("GetRolesForUser", "Account", new { userId = item.UserId });
                            <div>@Convert.ToString(roles)</div>
                        }
                    </td>
                    <td>
                        <a href="#" data-href="@Url.RouteUrl(routeName: "deleteuser", routeValues: new { id = item.UserId })" class = "delete-user" style = "display:none;">
                            Delete
                        </a>
                        <noscript>@Html.RouteLink("Delete", "delete", new { id = item.UserId })</noscript>
                    </td>
                </tr>
                            }
        </table>
        <div class="div-row" style="text-align:center;">
            @for (int i = 1; i <= Model.NumberOfPages; i++)
            {
                if (i == Model.CurrentPage)
                {
                    <p class="btn btn-default selected">@i</p>
                }
                else
                {
                    <a class="btn btn-default" href="#" onclick="loadUsers(this);" style="display:none;">@i</a>
                    <noscript><a class="btn btn-default" href="@Url.RouteUrl("users", new { page = @i})">@i</a></noscript>
                }
            }
        </div>
    </div>
</div>