MvcPL/ViewModels/PhotoViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MvcPL.ViewModels
{
    public class PhotoViewModel
    {
        [HiddenInput(DisplayValue=false)]
        public int Id { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public byte[] Image { get; set; }
        [HiddenInput(DisplayValue = false)]
        public DateTime CreatedOn { get; set; }

        [HiddenInput(DisplayValue = false)]
        public int CategoryId { get; set; }

        [HiddenInput(DisplayValue = false)]
        public int UserId { get; set; }
    }
}

MvcPL/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interface.Entities;
using BLL.Interface.Services;
using MvcPL.Infrastructure.Mappers;
using MvcPL.Infrastructure.Attributes;
using MvcPL.Infrastructure.Utilities;
using MvcPL.ViewModels;
using System.IO;
using System.Drawing.Imaging;

namespace MvcPL.Controllers
{
    public class PhotoController : Controller
    {
        #region Fields
        private readonly ICategoryPhotoService categoryService;
        private readonly IVotingService votingService;
        private readonly IPhotoService photoService;
        private readonly IUserService userService;
        #endregion

        #region Ctors
        public PhotoController(ICategoryPhotoService service, IPhotoService phService, IUserService usrService, IVotingService voteService)
        {
            categoryService = service;
            photoService = phService;
            userService = usrService;
            votingService = voteService;
        }
        #endregion

        #region Public Methods

        public ActionResult Index(int page = 1, int Id = 0)
        {
            int pageSize = 6;
            dynamic photosPerPages;
            if (Id > 0)
                photosPerPages = photoService.GetAllPhotoEntities().Where(ph => ph.CategoryId == Id).Select(photo => photo.ToMvcPhoto()).Skip((page - 1) * pageSize).Take(pageSize);
            else
                photosPerPages = photoService.GetAllPhotoEntities().Select(photo => photo.ToMvcPhoto()).Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = pageSize,
                TotalItems = photoService.GetAllPhotoEntities().Count()
            };

            IndexViewModel ivm = new IndexViewModel
            {
                PageInfo = pageInfo,
                Photos = photosPerPages
            };
            if (HttpContext.Request.IsAjaxRequest())
                return PartialView(ivm);
            return View(ivm);
        }

        [Authorize]
        public ActionResult GetPhotoForUser(int page = 0)
        {
            int pageSize = 3;
            int userId = userService.GetUserByEmail(User.Identity.Name).UserId;
            var photos = new PagedData<PhotoViewModel>();

            var allPhotos = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .ToList();

            if (page > 0)
            {
                photos.Data = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .Skip(pageSize * (page - 1))
                        .Take(pageSize)
                        .ToList();
                photos.CurrentPage = page;
            }
            else
            {
                photos.Data = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .Take(pageSize)
                        .ToList();
                photos.CurrentPage = 1;
            }
            photos.NumberOfPages = allPhotos.Count() % pageSize == 0 ? allPhotos.Count() / pageSize : allPhotos.Count() / pageSize + 1;


            return View(photos);
        }

        public ActionResult PhotosList(int page)
        {
            int pageSize = 3;
            int userId = userService.GetUserByEmail(User.Identity.Name).UserId;
            var photos = new PagedData<PhotoViewModel>();

            var allPhotos = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .ToList();

            photos.Data = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .Skip(pageSize * (page - 1))
                        .Take(pageSize)
                        .ToList();

            photos.NumberOfPages = allPhotos.Count() % pageSize == 0 ? allPhotos.Count() / pageSize : allPhotos.Count() / pageSize + 1;
            photos.CurrentPage = page;

            return PartialView(photos);
        }

        public ActionResult LastPhotos(string userName = null)
        {
            int userId = 0;
            if (userName == null)
                userId = userService.GetUserByEmail(User.Identity.Name).UserId;
            else
                userId = userService.GetUserByEmail(userName).UserId;
            var allPhotos = photoService.GetAllPhotoEntitiesForUser(userId).Select(photo => photo.ToMvcPhoto())
                        .ToList();

            var lastphotos = allPhotos.Skip(Math.Max(0, allPhotos.Count() - 6));

            return PartialView(lastphotos);
        }

        /// <summary>
        /// Method Photos dynamic load photos to main page.
        /// </summary>
        /// <param name="photoId">Id of last photos in main page.</param>
        /// <returns>Next 3 photos to main page.</returns>
        [HttpPost]
        public ActionResult Photos(int photoId, int Id = 0)
        {
            var photos = default(IEnumerable<PhotoViewModel>);
            if(Id > 0)
               photos = photoService.GetAllPhotoEntities().Select(photo => photo.ToMvcPhoto()).
                    Where(p => p.Id > photoId && p.CategoryId == Id).Take(3);
            else
               photos = photoService.GetAllPhotoEntities().Select(photo => photo.ToMvcPhoto()).
                    Where(p => p.Id > photoId).Take(3);
            if (photos.IsEmpty<PhotoViewModel>())
                return null;
            return PartialView("_Photos", photos);
        }

        [Authorize]
        [HttpGet]
        public ActionResult CreatePhoto()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreatePhoto(PhotoViewModel photo, IEnumerable<HttpPostedFileBase> files, string Id)
        {
            if (!ModelState.IsValid)
                return View(photo);
            if (files.Count() == 0 || files.FirstOrDefault() == null)
            {
                ViewBag.error = "Please choose a file";
                return View(photo);
            }

            PhotoViewModel model = new PhotoViewModel();
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {
                    model.Image = Images.GetImageNewSize(file);
                }

                model.Description = photo.Description;
                model.CreatedOn = DateTime.Now;
                model.CategoryId = Convert.ToInt32(Id);
                model.UserId = userService.GetUserByEmail(User.Identity.Name).UserId;
                photoService.CreatePhoto(model.ToBllPhoto());
            }

            return RedirectToAction("GetPhotoForUser");
        }

        [Authorize]
        [HttpGet]
        public ActionResult EditPhoto(int photoId)
        {
            var photo = photoService.GetPhotoEntity(photoId).ToMvcPhoto();
            return View(photo);
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditPhoto(PhotoViewModel photo, int photoId, int id)
        {
            if (ModelState.IsValid)
            {
                photo.Id = photoId;
                photo.CategoryId = id;
                photoService.UpdatePhoto(photo.ToBllPhoto());
                TempData["message"] = string.Format("Photo {0}  has been updated.", photo.Description);
                return RedirectToAction("GetPhotoForUser");
            }

            return View(photo);
        }

        [HttpGet]
        public ActionResult DeletePhoto(int id)
        {
            PhotoEntity photo = photoService.GetPhotoEntity(id);

            if (photo == null)
                return HttpNotFound();

            return View(photo.ToMvcPhoto());
        }

        [HttpPost, ActionName("DeletePhoto")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhotoEntity photo = photoService.GetPhotoEntity(id);
            TempData["message"] = string.Format("Photo has been deleted.", photo.Description);
            photoService.DeletePhoto(photo);
            return RedirectToAction("GetPhotoForUser");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            PhotoEntity photo = photoService.GetPhotoEntity(id);
            TempData["message"] = string.Format("Photo has been deleted.", photo.Description);
            photoService.DeletePhoto(photo);            
            return RedirectToAction("GetPhotoForUser");
        }

        public ActionResult FindByDescription(string term)
        {

            var photos = photoService.GetAllPhotoEntities().Where(photo => photo.Description.ToLower().Contains(term.ToLower()));
            var results = photos.Select(photo =>
                new
                {
                    id = photo.Id,
                    label = photo.Description
                });

            var jsonResult = Json(results.ToList(), JsonRequestBehavior.AllowGet);

            return jsonResult;
        }

        [HttpGet]
        public ActionResult Find()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Find(string term)
        {
            IEnumerable<PhotoViewModel> photos = photoService.GetAllPhotoEntities().Where(photo => photo.Description.ToLower().Contains(term.ToLower()) || photo.Description.ToLower() == term.ToLower()).
                Select(photo => new PhotoViewModel { CreatedOn = photo.CreatedOn, CategoryId = photo.CategoryId, Id = photo.Id });

            return View(photos);
        }

        public JsonResult PhotoListBySearch(string search)
        {
            var photos = photoService.GetAllPhotoEntities().Where(photo => photo.Description.ToLower().Contains(search.ToLower())).

MvcPL/Controllers/VotingController.cs
using BLL.Interface.Services;
using MvcPL.ViewModels;
using MvcPL.Infrastructure.Mappers;
using System.Web.Mvc;
using System.Linq;
using System;

namespace MvcPL.Controllers
{
    public class VotingController : Controller
    {
        #region Fields
        private readonly IVotingService votingService;
        private readonly IUserService userService;
        private readonly IPhotoService photoService;
        #endregion

        #region Ctors
        public VotingController(IPhotoService phService, IUserService usrService, IVotingService voteService)
        {
            photoService = phService;
            userService = usrService;
            votingService = voteService;
        }
        #endregion

        #region Public Methods

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AddVoting(string userName, int photoId, int rating)
        {
            int userId = userService.GetUserByEmail(userName).UserId;
            votingService.Create((new VotingViewModel() { UserId = userId, PhotoId = photoId, Rating = rating }).ToBllVoting());

            int raters = GetRaters(photoId);
            double totalRating = Math.Round(GetTotalRating(photoId), 1);
            var jsondata = new { Raters = raters, Rating = totalRating };

            return Json(jsondata);
        }

        public double GetTotalRating(int photoId)
        {
            double total = votingService.GetRatingForPhoto(photoId);

            return Math.Round(total, 1);
        }

        public int GetRaters(int photoId)
        {
            return votingService.GetRaters(photoId);
        }

        public bool CanVote(string userName, int photoId)
        {
            var user = userService.GetUserByEmail(userName);

            if (user != null)
                if (votingService.GetRatingForPhotoUser(photoId, user.UserId) > 0)
                    return false;

            return true;
        }

        public bool IsUserPhoto(string userName, int photoId)
        {
            var user = userService.GetUserByEmail(userName);

            if (user != null)
                if (photoService.GetPhotoEntity(photoId).UserId == user.UserId)
                    return true;

            return false;
        }

        #endregion
    }
}

MvcPL/Views/Photo/CreatePhoto.cshtml
@model MvcPL.ViewModels.PhotoViewModel

@{
    ViewBag.Title = "Create Photo";
    Layout = "~/Views/Shared/_PhotoLayout.cshtml";
}

<section class="central-div">
<h4>Add new Photo</h4>    
<hr>
    <div class="clearfix" style="width:10rem; float:left">
        @{Html.RenderAction("LastPhotos", "Photo");}
    </div>
@using (Html.BeginForm("CreatePhoto", "Photo", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => Model.Description, new { @class = "control-label col-sm-3" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Description, new { @placeholder = "Short Description", @class = "form-control required" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Category", new { @class = "control-label col-sm-3" })
        <div class="col-md-10">
            <div class="category-dropdown">
                @{Html.RenderAction("GetAllCategoryPhoto", "Category");}
                <span class="left-float">
                    @Html.RouteLink("+ Category", "categorycreate", routeValues: null, htmlAttributes: new { id = "categoryLink2", data_dialog_width = 350 })
                </span>
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Choose Image", new { @class = "control-label col-sm-3" })
        <div class="col-md-10">
            <label class="file-upload">
                <span class="button">Upload File</span>
                <mark></mark>
                <input type="file" multiple id="photo_path" name="files" accept=".jpg, .png, .gif" title="Choose file" onchange="previewFile()">
            </label>
            <img src="" class="img-preview" alt="Preview..." id="preview" style="display:none;">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label class="col-md-2"></label>
        <div class="col-md-10">
            <input type="submit" class="button btn" style="border:1px solid lightgray; width:50%;" value="Add" />
            @Html.ActionLink("Cancel", "Index", "Photo", null, new { @class = "link-btn btn" })
            <div style="color:red">
                @ViewBag.error
            </div>
        </div>
    </div>
}
</section>

MvcPL/Views/Photo/DeletePhoto.cshtml
@model MvcPL.ViewModels.PhotoViewModel

@{
    ViewBag.Title = "delete-photo";
    Layout = "~/Views/Shared/_PhotoLayout.cshtml";
}

<div class="central-div">
    <h4>Delete Photo</h4>
    <hr>
    <div style="width:50%; margin:0 auto;">
        <div>Are you sure you want to delete photo with description <b>@Html.DisplayFor(model => model.Description)</b>?</div>
        <br>
        <img src="@Url.RouteUrl("photoimg", new { photoId = Model.Id})" class="display-img" style="border: 1px solid #ddd;
    border-radius: 0.5rem;" alt="@Model.Description" />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <p>
                @Html.ActionLink("Back to photos", "GetPhotoForUser", null, htmlAttributes: new { @class = "link-btn btn" })
            </p>
            <p style="float:right; width:50%;">
                <input style="border:1px solid lightgray; width:100%;" type="submit" value="Delete" />
            </p>
        }
    </div>
</div>

MvcPL/Views/Photo/Details.cshtml
@model MvcPL.ViewModels.PhotoViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_PhotoLayout.cshtml";
}
<div class="central-div">
    <h4>Photo Details: @Model.Description</h4>
    <hr>
    <div id="description-photo">
        <img src="@Url.RouteUrl("photoimg", new { photoId = Model.Id})" />
        <div id="about-photo">
            <p>@Model.CreatedOn</p>
            <p>@Html.ActionLink("Back to main page", "Index")</p>
        </div>
    </div>
</div>

MvcPL/Views/Photo/EditPhoto.cshtml
@model MvcPL.ViewModels.PhotoViewModel

@{
    ViewBag.Title = "Edit Photo";
    Layout = "~/Views/Shared/_PhotoLayout.cshtml";
}

<div class="central-div">
    <h4>Edit @Model.Description</h4>
    <hr>
    <div style="float:left; width:40%; margin-left:6em;">
        <img id="@Model.Id" src="/images/@Model.Id" class="display-img" style="border: 1px solid #ddd;
    border-radius: 0.5rem;" />
    </div>
    <div class="edit-img">
    @using (Html.BeginForm("EditPhoto", "Photo", FormMethod.Post))
    {
        <div class="form-group clearfix">
            @Html.LabelFor(m => m.Description, new { @class = "col-md-2 edit-label" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group clearfix" style="margin-top: 1em;">
            @Html.Label("Category", new { @class = "col-md-2 edit-label" })
            <div class="col-md-10">
                <div class="category-dropdown">
                    @{Html.RenderAction("GetAllCategoryPhoto", "Category", new { id = Model.CategoryId });}
                </div>
           </div>
        </div>
        <br>
        <div class="form-group">
            <label class="col-md-2"></label>
            <div class="col-md-10">
            <input type="submit" class="btn edit-save" style="border:1px solid lightgray;" value="Save" />
              @Html.ActionLink("Cancel", "GetPhotoForUser", null, new { @class = "btn edit-cancel", style = "color:black;" })
        </div>
    </div>
    }
    </div>
</div>

MvcPL/Views/Photo/Find.cshtml
@model IEnumerable<MvcPL.ViewModels.PhotoViewModel>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_PhotoLayout.cshtml";
}

<section class="central-div">
    <h4>Result of search</h4>
    <hr>
    <div class="div-table" id="search-photos">
        @{var counter = 1; }
        <div class="div-row">
            @foreach (var photo in Model)
            {
                <div class="div-cell">
                    <a onclick='aboutPhoto(this)' data-ajax='true' data-ajax-mode='replace' data-ajax-update='#photoTemplate' href='photo/details?photoId=@photo.Id'>
                        <img src='/images/@photo.Id' width="100" height="100" />
                    </a>
                </div>
                if (counter % 3 == 0)
                {
                    @:</div><div class="div-row">
                }
                counter++;
            }
        </div>
    </div>
    <div class="about-photo">
    <span id="search-photo" class="left-float"></span>   
    <div class="selected-photo" style="display:none">
       <div class="clearfix">
           <p class="photo-description">
           </p>
           <img src="" alt="Photo" class="display-img" />
       </div>
       <br style="clear:both;" />
   </div>        
    </div>
</section>

MvcPL/Views/Photo/GetPhotoForUser.cshtml
@model MvcPL.ViewModels.PagedData<MvcPL.ViewModels.PhotoViewModel>

@{
    ViewBag.Title = "My Photo";
    Layout = "~/Views/Shared/_PhotoLayout.cshtml";
}

<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/load-user-photos.js"></script>
<script src="~/Scripts/dialog-login-registry.js"></script>
<script src="~/Scripts/confirm-delete.js"></script>
<script src="~/Scripts/photo-album.js"></script>

<div style="width:60%; margin:0 auto;">
    <p style="width:50%;">@Html.ActionLink("Add Photo", "CreatePhoto", routeValues: null, htmlAttributes: new { @class = "link-btn btn" })</p>
    <p style="width:50%">@Html.RouteLink("Add Category", "categorycreate", routeValues: null, htmlAttributes: new { id = "categoryLink", @class = "link-btn btn", data_dialog_width = 350 })</p>
</div>
<br>
<div id="photos-list">
    @if (TempData["message"] != null)
    {
        <div>
            @TempData["message"]
        </div>
    }
        @Html.Partial("PhotosList")
</div>

MvcPL/Views/Photo/Index.cshtml
@using MvcPL.Infrastructure.Helpers
@model MvcPL.ViewModels.IndexViewModel

@{
    ViewBag.Title = "Photo Album";
}

<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/load-photos.js"></script>
<script src="~/Scripts/rating-photos.js"></script>

<div class="div-table  grid cs-style-3 clearfix" id="allphoto">
    @{var counter = 1;}
    <div class="div-row">
        @foreach (var item in Model.Photos)
{
            <div class="div-cell">
                <figure>
                    @Html.Partial("_Photo", item)
                    <figcaption id="@item.Id">
                        @Html.Partial("_AboutPhoto", item)
                    </figcaption>
                    <noscript>
                    <span style="display:block; width:300px; height:380px;">
                        You need enable javascript to vote.
                        @Html.Partial("_AboutPhoto", item)
                    </span>
                    </noscript>
                </figure>
            </div>
            if (counter % 3 == 0)
            {
                @:</div><div class="div-row">
            }
            counter++;
        }
    </div>
</div>
<noscript>
    <div class="div-row" style="text-align:center;">
        @Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new { page = x }))
    </div>
</noscript>
@Html.Hidden("User", User.Identity.Name)
@Scripts.Render("~/bundles/jqueryval")

MvcPL/Views/Photo/LastPhotos.cshtml
@model IEnumerable<MvcPL.ViewModels.PhotoViewModel>

<div class="div-table" id="search-photos">
    <div class="div-row">
        @foreach (var photo in Model)
            {
            <div class="div-cell">
                <img src='/images/@photo.Id' width="100" height="100" />
            </div>
        }
    </div>
</div>

MvcPL/Views/Photo/PhotosList.cshtml
@model MvcPL.ViewModels.PagedData<MvcPL.ViewModels.PhotoViewModel>

<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.0.min.js"></script>
<script src="~/Scripts/load-user-photos.js"></script>
@Scripts.Render("~/bundles/jqueryval")
<div class="div-table">
    @{var counter = 1;}
    <div class="div-row">
        @foreach (var item in Model.Data)
        {
            <div class="div-cell" id="@item.Id">
                <img src="@Url.RouteUrl("photoimg", new { photoId = item.Id})" class="display-img" alt="@item.Description" />
                <div>
                    <noscript>
                        <a href="@Url.RouteUrl(routeName: "photodelete", routeValues: new { id = item.Id })" class="right-float">
                            <img src="~/Content/images/delete-photo.png" class="delete-non-ajax" alt="Delete Photo" />
                        </a>
                    </noscript>
                    <a href="#" data-href="@Url.RouteUrl(routeName: "photodel", routeValues: new { id = item.Id })" class="delete-photo" style="display:none"></a>
                    <a href="@Url.Action("CreatePhoto", "Photo")" class="right-float">
                        <img src="~/Content/images/add-photo.png" class="photo" alt="Add Photo" />
                    </a>
                    <a class="confirm right-float" href="@Url.Action("EditPhoto", "Photo", routeValues: new { photoId = item.Id })">
                        <img src="~/Content/images/edit-photo.png" class="photo" alt="Edit Photo" />
                    </a>
                </div>
            </div>
            if (counter % 3 == 0)
            {
                @:</div><div class="div-row">
            }
            counter++;

        }
    </div>
    <div style="clear:both;"></div>
        <div class="div-row" style="text-align:center;">
            @for (int i = 1; i <= Model.NumberOfPages; i++)
            {
                if (i == Model.CurrentPage) {
                    <p class="btn btn-default selected">@i</p>
                }
                else {
                    <a class="btn btn-default" href="#" onclick="loadUserPhoto(this);" style="display:none;">@i</a>
                    <noscript><a class="btn btn-default" href="@Url.RouteUrl("userphotos", new { page = @i})">@i</a></noscript>
                }
            }
        </div>
    </div>

MvcPL/Views/Photo/_AboutPhoto.cshtml
@using MvcPL.Infrastructure.Helpers
@using MvcPL.ViewModels
@model PhotoViewModel

@if (User.IsInRole("User"))
{
    var canVote = Html.Action("CanVote", "Voting", new { userName = User.Identity.Name, photoId = Model.Id });
    var isUserPhoto = Html.Action("IsUserPhoto", "Voting", new { userName = User.Identity.Name, photoId = Model.Id });
    if (Convert.ToBoolean(isUserPhoto.ToString()) == true)
    {
        <div class="vote-div"> It's your photo :)</div>
    }
    else if (Convert.ToBoolean(canVote.ToString()) == true)
    {
        @Html.Ratings(new VotingViewModel() { PhotoId = @Model.Id })        
    }
    else
    {
        <div class="vote-div"> You already vote!</div>
    }
}
else
{
    <div class="vote-div"> Sign Up for rate photo!</div>
}
<div class="left-float">
    <span id="totalRating-@Model.Id">@Html.Action("GetTotalRating", "Voting", new { photoId = Model.Id })</span>
    <img src="~/Content/images/star.png" alt="Star" />
    By <span id="totalRaters-@Model.Id">@Html.Action("GetRaters", "Voting", new { photoId = Model.Id })</span> rater(s)
</div>
<div class="left-float">Description: @Model.Description</div>
<div class="left-float">Category: @Html.Action("GetCategory", "Category", new { categoryId = Model.CategoryId })</div>

@section Scripts
{
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPL/Views/Photo/_Photo.cshtml
@model MvcPL.ViewModels.PhotoViewModel

<div class="results">
    <img id="img_@Model.Id" src="@Url.RouteUrl("photoimg", new { photoId = Model.Id})" class="source-photo" alt="@Model.Description" />
</div>

@section Scripts
{
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPL/Views/Photo/_Photos.cshtml
@model IEnumerable<MvcPL.ViewModels.PhotoViewModel>

<script src="~/Scripts/rating-photos.js"></script>

<div class="div-row">
    @foreach (var item in Model)
    {
        <div class="div-cell">
            <figure>
                @Html.Partial("_Photo", item)
                <figcaption id="@item.Id">
                    @Html.Partial("_AboutPhoto", item)
                </figcaption>
                <noscript>
                    <div style="min-height: 27.1rem;width : 21.2rem;">@Html.Partial("_AboutPhoto", item)</div>
                </noscript>
            </figure>
        </div>
    }
</div>
@Scripts.Render("~/bundles/jqueryval")